version: "3"

# // Следует учитывать, что docker-composes работает с сервисами.
# // 1 сервис = 1 контейнер.
# // Раздел, в котором будут описаны сервисы, начинается с 'services'.

services:

  # // Сервис - контейнер, созданный из Dockerfile
  # // Назвать его можно так, как хочется.
  # // Понятное название сервиса помогает определить его роль.
  # // Здесь мы, для именования соответствующего сервиса, используем ключевое слово 'python'.
  Playwrite:

    # // Ключевое слово "build" позволяет задать
    # // путь к файлу Dockerfile, который нужно использовать для создания образа,
    # // который позволит запустить сервис.
    # // Здесь . соответствует текущему пути
    build: .

    # // указываем название образа, который получится в процессе билда
    image: playwright-docker

    # // имя контейнера, который будет стартовать от образа
    container_name: playwright_All_Browsers

    # // Команда, которую нужно запустить после создания образа.
    # // Следующая команда означает запуск python-скрипта
    command: npx playwright test  
  