name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f "docker-compose-GRID.yml" up -d --build
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps  
      - name: Test
        run:  npx playwright test --headed --config=docker.config.js
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
         name: video-report
         path: tmp/videos/
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose-GRID.yml" down